### ISSUE TITLE
Call for contributions and feature requests

### ISSUE THREAD

**Issue by castle-lemongrab** [castlelemongrab/parlance#20]
If you have any ideas, small or large, for how this codebase could be improved, please comment in this thread or file a new issue and reference it here so it can be added to the kanban board. No idea is too small or too big. If we're going to do free speech, let's go all the way.

**Comment by ih8github** [comment]
Idea:  allow a connection string that takes a username and password 

Also, it would be nice to query network wide data like all usernames

**Comment by castle-lemongrab** [comment]
The login process currently uses SMS verification and a Captcha; this is not only difficult to implement, but likely would circumvent a technical access control and be prohibited under the Parler terms of service. So it's unlikely. However, the client does handle server-initiated rotation of credentials, so there shouldn't be a need to log in more than once.

**Comment by ih8github** [comment]
Could we do follow and unfollow? That would be really powerful.

For instance if parlance did that then I could write a script calling it that does a diff on who I follow vs who follows me and unfollows users who aren’t following back after X days if they have less than N followers (i.e. unfollow non-influential users who don’t follow me back after a while).

**Comment by castle-lemongrab** [comment]
Yeah, I can file issues for follow and unfollow.

**Comment by greggh** [comment]
I would like to feed in a file generated by parlance to the follow or unfollow function. So I could use parlance to generate a list of people who follow one specific user, and then run it through my account unfollowing any of them. Or in reverse of course, generate a list and then follow.

**Comment by castle-lemongrab** [comment]
The above could probably be accomplished using a pipeline containing Parlance and a utility like `jq` – using the `follow` and `unfollow` CLI subcommands in conjunction with the `followers` or `following` CLI subcommands. For each follower/following user, you'd invoke `parlance follow` or `parlance unfollow` in a loop.

I could see bringing a feature like that in-process if (i) there was a compelling large-scale research use case, and (ii) the repeated Node interpreter (or HTTP < 2 connection) startup time in the above approach was too large.
