### ISSUE TITLE
Be Node v8+ compatible (was: Credentials / init keeps failing)

### ISSUE THREAD

**Issue by ih8github** [castlelemongrab/parlance#22]
Is it possible to provide an example of how to connect parlance to Parler?

I’ve tried supplying both URI encoded and decoded values directly to the —mst and —jst options as well as putting them into the auth.json file. I’ve tried including entire cookies as well as just the content/value strings within the cookies. Not sure what else to try.

Also, I am a bit confused why it would want both a -c option that presumably points to the json file with the mst and jst, while also requiring the same data as —mst and —jst sub-options to -c.

**Comment by castle-lemongrab** [comment]
Sure thing, I'll take another look. The `-c` option is a credentials input file, and the `-o` option is a credentials output file. The latter serves a dual purpose – it specifies an output file to persist new tokens to for when the server rotates the JST or MST token (they're also updated in memory during the run). The `-c` option is the credentials configuration to be read on startup.

These can be set same file (and in theory could have been a single option), but potentially overwriting user-provided credentials automatically seemed like a bad idea – bugs (including server bugs or authentication method changes) could in theory cause data loss.

Do you have a quick example of the commands you're running and the error message you're receiving (minus the actual token values)? I can provide a more detailed example in the README.md file and potentially improve the process once I'm certain where the issue/confusion is.

**Comment by ih8github** [comment]
Thanks!  Yes here are some examples:

# Example 1 (manually decoded mst and jst via https://www.urldecoder.org/)

sudo parlance init -c "/parlance/config/auth.json" --mst "s:px4aMzMFWMX4bGDyXi6NxISja39SixY1Zn8LoqFotouvyq5e6CLqGTx2j8o6ULJUw4GdzhXbmwHLpHmooiueWLKbkYel6H9SCk8gejjO1Ss5guRtQH0dUdaW8K14eTm7.tqfaVjsQCJSKVPVbxWnx67yPsXJfbown2OTSgESfjXs" --jst "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOjM4NBAwMjYsInVzZXJJZCI6Mjg2ODIzOCwicGVybWlzc2lvbnMiOjAsInZlcmlmaWVkIjpmYWxzZSwiaWF0IjoxNTkzOTY3NTUxLCJleHAiOjE1OTM5Njc4NTF9.JfHM88vhF5aSZ6ntjtg_qtnG2WORGk24uMGcs20sJ5YhMv4BOxS67U65Y0TBsi5r5VU8tnvn-6_y2It1sshrmQ" -o "/parlance/config/auth.json"
[fatal] Failed to update credentials file

# Example 2 (same but stores the mst and jst in a file - prepopulated -c file)

parlance init -c "parlerbot/cookies/cookies_decoded" --mst "/parlerbot/cookies/cookies_decoded_mst" --jst "/parlerbot/cookies/cookies_decoded_jst" -o "parlance/config/auth.json" 
[fatal] Failed to update credentials file


# Example 3 (same but -c file is in its blank default state)

parlance init -c "/parlance/config/auth.json" --mst "/parlerbot/cookies/cookies_decoded_mst" --jst "/parlerbot/cookies/cookies_decoded_jst" -o "parlance/config/auth.json" 
[fatal] Failed to update credentials file


I changed a couple of characters in the cookie values for this example so no one hacks my account.

**Comment by castle-lemongrab** [comment]
Can repeat example number one with `cd parlance`, then `parlance init --mst "$mst" --jst "$jst" -o config/auth.json`, then try `parlance profile`?

The `--mst` and `--jst` options accept strings (not filenames – yet anyway), and there should be no need to use `-c` with `parlance init`; that option isn't intended to be applicable to the `init` subcommand.

If that works, I can tighten up the argument validation and error messages, and add a bit more documentation. The utility also shouldn't need root privileges to run (only potentially to install, if you're using a system `npm`).

**Comment by ih8github** [comment]
Thanks again. I both installed it with `npm -g` and also cloned the repo in case I wanted to try changing something. Not sure if it may get confused by the fact that it's running the npm-installed program and I was specifying the "auth.json" from the downloaded repo.

So, I cd into 'parlance' (downloaded from GitHub) and ran:

parlance init  --mst "s:px4aMzMFWMX4bGDyXi6NxISja39SixW1Zn8LoqFotouvyq5e6CLqGTx2j8o6ULJUw4GdzhXbmwHLpHmooiueWLKbkYel6H9SCk8gejjO1Ss5guRtQH0dUdaW8K14eTm7.tqfaVjsQCKSKVPVbxWnx67yPsXJfbown2OTSgESfjXs" --jst "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOjM4NDAwMjYsInVzZXJJZCI6Mjg2ODIzOCwicGVybWlzc2lvbnMiOjAsInZlcmlmaWVkIjpmYWxzZSwiaWF0IjoxNTkzOTY3NTUxLCJleHAiOjE1OTM5Njc4NKF9.JfHM88vhF5aSZ6ntjtg_qtnG2WORGk24uMGcs20sJ5YhMv4BOxS67U65Y0TBsi5r5VU8tnvn-6_y2It1sshrmQ" -o "config/auth.json"
[fatal] Failed to update credentials file

Next try, I reset the auth.json to its original state:

parlance init  --mst "s:px4aMzMFWMX4bGDyXi6NxISja39SixW1Zn8LoqFotouvyq5e6CLqGTx2j8o5ULJUw4GdzhXbmwHLpHmooiueWLKbkYel6H9SCk8gejjO1Ss5guRtQH0dUdaW8K14eTm7.tqfaVjsQCJSKVPVbxWnx67yPsXJfbown2OTSgESfjXs" --jst "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSSQiOjM4NDAwMjYsInVzZXJJZCI6Mjg2ODIzOCwicGVybWlzc2lvbnMiOjAsInZlcmlmaWVkIjpmYWxzZSwiaWF0IjoxNTkzOTY3NTUxLCJleHAiOjE1OTM5Njc4NTF9.JfHM88vhF5aSZ6ntjtg_qtnG2WORGk24uMGcs20sJ5YhMv4BOxS67U65Y0TBsi5r5VU8tnvn-6_y2It1sshrmQ" -o "config/auth.json"
[fatal] Failed to update credentials file

Same result. 1 more try with the raw (encoded) cookie data from my Cookie Manager plugin for Firefox just in case it was decoded wrong:

parlance init --mst "s%3Apx4aMzMFWMX4bGDyXi6NxISja39SixW1Zn8LoqFotouvyq5e6CLqGTx2j8o6ULJUw4GdzhXbmwHLpHmooiueWLKbkYel6H9SCk8gejjO1Ss5guRtQH0dUdaW8K14eTm7.tqfaVjsQCJSKVPVbxWnx67yPsXJfbown2OTSgESfjXs" --jst "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOjM4NDAwMjYsInVzZXJJZCI6Mjg2ODIzOCwicGVybWlzc2lvbnMiOjAsInZlcmlmaWVkIjpmYWxzZSwiaWF0IjoxNTkzOTY3NTUxLCJleHAiOjE1OTM5Njc4NTF9.JfHM88vhF5aSZ6ntjtg_qtnG2WORGk24uMGcs20sJ5YhMv4BOxS67U65Y0TBsi5r5VU8tnvn-6_y2It1sshrmQ" -o "config/auth.json"
[warn] Detected invalid URI-encoded credentials; correcting
[fatal] Failed to update credentials file

**Comment by ih8github** [comment]
parlance profile also throw an error about being unable to read config/auth.json

**Comment by castle-lemongrab** [comment]
It'd be really helpful to edit out the token values from these comments, so people don't attempt to use them and/or falsely think they're a security issue/leak.

Does `config/auth.json` exist in your current working directory when you run `parlance profile`? It's also possible to just edit the JSON credentials file by hand; it's a simple JSON object (the `init` command was originally and ironically intended for convenience).

**Comment by ih8github** [comment]
I can edit them out of the comments sure (I already changed a few characters arbitrarily for security).

So basically I should put the same strings in auth.json and then I don’t need to use init? Let me try that now.

**Comment by castle-lemongrab** [comment]
Yeah, it's just a regular JSON file, one top-level object, with an `mst` property (a URI-decoded string) and a `jst` property (also a URI-decoded string).

**Comment by ih8github** [comment]
Okay. I tried it that way but I’m still getting the error “unable to read authorization data from config/auth.json”

I tried parlance profile with and without the -c option but it made no difference

**Comment by ih8github** [comment]
Not sure if this is relevant but I notice that when I search my system for the npm installed copy of parlance and I find the .tgz archive there’s no config folder in it like there is in the GitHub repo. I wonder if somehow it’s looking there instead of the folder and file I’m trying to point it to?

But I guess that doesn’t explain why the —mst and —jst options didn’t work

**Comment by castle-lemongrab** [comment]
```
parlance init --mst "$mst" --jst "$jst" -o "config/auth.json"
[fatal] Failed to update credentials file
```

Assuming the `./config` directory exists, this is unexpected. I'll try to reproduce today.

**Comment by castle-lemongrab** [comment]
Here's what I'm seeing on Linux ARM64 (aarch64), Raspbian, with a system-installed Node.js version 10.12:
```
$ mkdir -p config
$ sudo npm install -g parlance
+ parlance@1.3.1
added 1 package from 1 contributor in 1.197s
$ parlance init --mst 's%3A...' --jst 'ey...' -o config/auth.json
[warn] Detected invalid URI-encoded credentials; correcting
[credentials] Credentials file was updated
$ ls -al config/auth.json 
-rw-r--r-- 1 lemon lemon 468 Jul  5 23:16 config/auth.json
$ parlance profile -c config/auth.json
[network] Fetching v1/profile
[
  ...
]
$ parlance profile 
[network] Fetching v1/profile
[
  ...
]
$ parlance init --mst 's%3...' --jst 'eyJ... -o config/auth.json
[warn] Detected invalid URI-encoded credentials; correcting
[credentials] Credentials file was updated
```

Are you certain the target directory exists and is writable by the user running `parlance init`?

**Comment by castle-lemongrab** [comment]
Okay, that version number is not right; one second. Can you run `node --version` and `parlance --version` for me real quick?

**Comment by castle-lemongrab** [comment]
Comedy option: rename to `parlaid`

**Comment by ih8github** [comment]
npm version is 3.5.2

parlance version is 1.41.0

**Comment by castle-lemongrab** [comment]
This is weird. I'm having trouble reproducing. Let me get an Ubuntu box and try. Do you know what version of Ubuntu you're on? This is worth testing from a clean install IMO.

**Comment by ih8github** [comment]
Ubuntu 18.04.1 

I can offer to try it on Trisquel as well

**Comment by castle-lemongrab** [comment]
I'll get a clean box; give me a couple hours.

**Comment by castle-lemongrab** [comment]
What's your `node --version`? I'm seeing some issues on versions of node that don't support `fs.promises`.

**Comment by ih8github** [comment]
v8.10.0

**Comment by castle-lemongrab** [comment]
Aha. There we go. It doesn't support an API we rely on. Let me see if I can extend compatibility downward from v10, as v8 is pretty common on cloud instances, and I think it's just the `fs` API.

**Comment by ih8github** [comment]
Thanks. I will also try upgrading to confirm on my end if my Ubuntu supports it.

**Comment by castle-lemongrab** [comment]
Sure thing; I suspect `writeFileSync` would be a reasonable and non-intrusive fallback for Node v8; will look at it.

**Comment by ih8github** [comment]
It worked!!!!! <3

I am on node v14 now and the problem is solved. Thanks for all your help.

**Comment by castle-lemongrab** [comment]
I've added support towadg Node v8+.

**Comment by castle-lemongrab** [comment]
This appears to work now on Node `v8.10.0`. Suggest refactoring the `async .promise.writeFile/readfile` and the `.writeFile/.readFile` into a central location prior to release – there's technically a difference between async waits and syscall-blocking waits, but we probably don't care right now.

**Comment by castle-lemongrab** [comment]
Remaining to-do: ensure a warning is emitted if `-c` is provided during `parlance init`. Or... maybe something more intelligent, I don't know. The idea is to not do what CouchDB does and overwrite user-provided configuration files at random, creating all hell for sysops and SREs.

**Comment by castle-lemongrab** [comment]
This should work with Node v8 now. Documentation updated. Acceptable. Reopen if you have any issues on Node v8.
