### ISSUE TITLE
Feature request: Ability to specify a date to scrape back from

### ISSUE THREAD

**Issue by sipka** [castlelemongrab/parlance#43]
Currently, when fetching Parlies based on hashtag / user, the results are returned from that moment in time, backwards. It would be very helpful, for research purposes, if a user would be able to specify the date to crawl back from.

For example, if one is investigating activity around elections time on #maga hashtag, right now it would take days of scraping to get to election time data, as this is a high activity hashtag.

I am not sure if this is easy to do or not, although the fact that system message seems to include some date is a positive sign (e.g. the startkey part of `Fetching v1/post/hashtag?tag=maga&limit=10&startkey=2020-11-25T21%3A24%3A27.365Z_250881603` )

**Comment by castle-lemongrab** [comment]
Take a look at #42 (in progress) – I think this will achieve exactly what you're looking for. If not, let me know.

**Comment by sipka** [comment]
Exactly. Yes. Perfect. Thank you!
