### ISSUE TITLE
Set-cookie headers on response

### ISSUE THREAD

**Issue by aadvdh** [castlelemongrab/parlance#46]
Hello,

Sorry for having to contact you this way, but i have been stuck on this for a while. I'm creating my own implementation based on making calls from a nodejs server. I'm running it on https://localhost:3000. While providing the jst and mst from the frontend to the backend the requests go through without any problems. That is, until the jst expires. I never get any set-cookies header back in the response headers. Honestly I feel like i'm missing something really fundamental. I would really appreciate it if you had an answer for this. I will try and see if I can help with a few open issues.

Thanks for reading.

**Comment by castle-lemongrab** [comment]
You might take a look at the `-c` option in Parlance. As far as I've been able to tell, my account successfully validates even if the (signed) JWT (`jst` cookie) is expired – and then goes on to do horrible things (long timeouts, HTTP 500s) if the JWT in the `jst` cookie is corrupt.

Do you by chance have a protocol dump of what you're seeing when attempting to use an expired (but signed) JWT as a `jst` cookie? It's been a bit of a mystery to us – they seemed intent on rotating it as a short-lived credential early on, but we can't currently see any enforcement at all.

**Comment by aadvdh** [comment]
Thanks for your answer. I'll try to get you a dump asap. The funny thing is once I completely removed the jst, and only sent the mst it actually continued to work. It's like you said, the intent seems for them to use a short lived credentials, but there is no enforcement whatsoever.
